on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    name: test workflow
    steps:
      - uses: actions/checkout@v2

      - name: Install hcl2json
        run: |
          brew install hcl2json
